package com.charityright.charityauthority.auditor.model.DraftResponse

data class SiteVisitReport(
    val absent_std: String,
    val absent_teacher: String,
    val approx_meal_price: String,
    val assign_task: String,
    val task_id: String,
    val assign_time: String,
    val audit_signature: Any,
    val auditor_id: String,
    val avg_age_std: String,
    val create_at: String,
    val date: String,
    val edu_type: String,
    val efficiency_other: String,
    val id: String,
    val meal_quality: String,
    val perfomance: String,
    val present_std: String,
    val present_teacher: String,
    val reason_absent: String,
    val remarks: String,
    val report_title: String,
    val school_id: String,
    val school_time: String,
    val section: String,
    val status: String,
    val suggestion: String,
    val teacher_signature: Any,
    val total_std: String,
    val total_teacher: String,
    val updated_at: String,
    val zone_id: String
)